CREATE TYPE "Role" AS ENUM ('OWNER', 'STAFF');
CREATE TYPE "StockMovementKind" AS ENUM ('INITIAL', 'ADJUSTMENT', 'SALE', 'REVERSAL');
CREATE TYPE "SyncOperationKind" AS ENUM ('CREATE', 'UPDATE', 'DELETE', 'SALE', 'DEBT_PAYMENT', 'IMPORT');
CREATE TYPE "SyncStatus" AS ENUM ('APPLIED', 'CONFLICT', 'REJECTED');
CREATE TYPE "ConflictType" AS ENUM ('STALE_EDIT', 'STOCK_SHORTAGE');
CREATE TYPE "ConflictStatus" AS ENUM ('OPEN', 'RESOLVED');
CREATE TABLE "Shop" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Shop_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" UUID NOT NULL, "email" TEXT NOT NULL, "name" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "mustChangePassword" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShopMembership" ("shopId" UUID NOT NULL, "userId" UUID NOT NULL, "role" "Role" NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ShopMembership_pkey" PRIMARY KEY ("shopId", "userId"));
CREATE TABLE "Product" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "name" TEXT NOT NULL, "category" TEXT NOT NULL DEFAULT '', "unit" TEXT NOT NULL, "stock" DECIMAL(18,3) NOT NULL DEFAULT 0, "lowStock" DECIMAL(18,3) NOT NULL DEFAULT 0, "costMinor" BIGINT NOT NULL, "priceMinor" BIGINT NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Product_pkey" PRIMARY KEY ("id"));
CREATE TABLE "StockMovement" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "productId" UUID NOT NULL, "saleId" UUID, "operationId" UUID, "kind" "StockMovementKind" NOT NULL, "quantity" DECIMAL(18,3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "StockMovement_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Sale" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "staffId" UUID NOT NULL, "invoiceNo" TEXT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "paymentType" TEXT NOT NULL, "customerName" TEXT NOT NULL, "customerPhone" TEXT NOT NULL DEFAULT '', "customerAddress" TEXT NOT NULL DEFAULT '', "driver" TEXT NOT NULL DEFAULT '', "car" TEXT NOT NULL DEFAULT '', "subtotalMinor" BIGINT NOT NULL, "deliveryFeeMinor" BIGINT NOT NULL DEFAULT 0, "discountMinor" BIGINT NOT NULL DEFAULT 0, "totalMinor" BIGINT NOT NULL, "amountPaidMinor" BIGINT NOT NULL, "balanceMinor" BIGINT NOT NULL, "payCashMinor" BIGINT NOT NULL DEFAULT 0, "payTransfer1Minor" BIGINT NOT NULL DEFAULT 0, "payTransfer2Minor" BIGINT NOT NULL DEFAULT 0, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Sale_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SaleItem" ("id" UUID NOT NULL, "saleId" UUID NOT NULL, "productId" UUID NOT NULL, "name" TEXT NOT NULL, "unit" TEXT NOT NULL, "quantity" DECIMAL(18,3) NOT NULL, "unitPriceMinor" BIGINT NOT NULL, "subtotalMinor" BIGINT NOT NULL, CONSTRAINT "SaleItem_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Debt" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "saleId" UUID NOT NULL, "customerName" TEXT NOT NULL, "phone" TEXT NOT NULL DEFAULT '', "originalAmountMinor" BIGINT NOT NULL, "balanceMinor" BIGINT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Debt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DebtPayment" ("id" UUID NOT NULL, "debtId" UUID NOT NULL, "operationId" UUID, "amountMinor" BIGINT NOT NULL, "occurredAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DebtPayment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShopSettings" ("shopId" UUID NOT NULL, "address" TEXT NOT NULL DEFAULT '', "phone" TEXT NOT NULL DEFAULT '', "version" INTEGER NOT NULL DEFAULT 1, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ShopSettings_pkey" PRIMARY KEY ("shopId"));
CREATE TABLE "RefreshSession" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RefreshSession_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SyncOperation" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "deviceId" TEXT NOT NULL, "userId" UUID NOT NULL, "kind" "SyncOperationKind" NOT NULL, "entityType" TEXT NOT NULL, "entityId" UUID NOT NULL, "baseVersion" INTEGER, "payload" JSONB NOT NULL, "clientTime" TIMESTAMP(3) NOT NULL, "serverSequence" BIGSERIAL NOT NULL, "status" "SyncStatus" NOT NULL, "error" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SyncOperation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SyncConflict" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "operationId" UUID, "type" "ConflictType" NOT NULL, "entityType" TEXT NOT NULL, "entityId" UUID NOT NULL, "serverPayload" JSONB NOT NULL, "submittedPayload" JSONB NOT NULL, "status" "ConflictStatus" NOT NULL DEFAULT 'OPEN', "resolution" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "resolvedAt" TIMESTAMP(3), CONSTRAINT "SyncConflict_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ImportBatch" ("id" UUID NOT NULL, "shopId" UUID NOT NULL, "fingerprint" TEXT NOT NULL, "summary" JSONB NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ImportBatch_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "ShopMembership_userId_idx" ON "ShopMembership"("userId");
CREATE INDEX "Product_shopId_updatedAt_idx" ON "Product"("shopId", "updatedAt");
CREATE UNIQUE INDEX "StockMovement_operationId_key" ON "StockMovement"("operationId");
CREATE INDEX "StockMovement_shopId_createdAt_idx" ON "StockMovement"("shopId", "createdAt");
CREATE INDEX "Sale_shopId_updatedAt_idx" ON "Sale"("shopId", "updatedAt");
CREATE UNIQUE INDEX "Sale_shopId_invoiceNo_key" ON "Sale"("shopId", "invoiceNo");
CREATE UNIQUE INDEX "Debt_saleId_key" ON "Debt"("saleId");
CREATE INDEX "Debt_shopId_updatedAt_idx" ON "Debt"("shopId", "updatedAt");
CREATE UNIQUE INDEX "DebtPayment_operationId_key" ON "DebtPayment"("operationId");
CREATE UNIQUE INDEX "RefreshSession_tokenHash_key" ON "RefreshSession"("tokenHash");
CREATE INDEX "RefreshSession_userId_idx" ON "RefreshSession"("userId");
CREATE INDEX "SyncOperation_shopId_serverSequence_idx" ON "SyncOperation"("shopId", "serverSequence");
CREATE UNIQUE INDEX "SyncOperation_shopId_id_key" ON "SyncOperation"("shopId", "id");
CREATE INDEX "SyncConflict_shopId_status_idx" ON "SyncConflict"("shopId", "status");
CREATE UNIQUE INDEX "ImportBatch_shopId_fingerprint_key" ON "ImportBatch"("shopId", "fingerprint");
ALTER TABLE "ShopMembership" ADD CONSTRAINT "ShopMembership_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShopMembership" ADD CONSTRAINT "ShopMembership_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Product" ADD CONSTRAINT "Product_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Sale" ADD CONSTRAINT "Sale_staffId_fkey" FOREIGN KEY ("staffId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SaleItem" ADD CONSTRAINT "SaleItem_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SaleItem" ADD CONSTRAINT "SaleItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Debt" ADD CONSTRAINT "Debt_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Debt" ADD CONSTRAINT "Debt_saleId_fkey" FOREIGN KEY ("saleId") REFERENCES "Sale"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DebtPayment" ADD CONSTRAINT "DebtPayment_debtId_fkey" FOREIGN KEY ("debtId") REFERENCES "Debt"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShopSettings" ADD CONSTRAINT "ShopSettings_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RefreshSession" ADD CONSTRAINT "RefreshSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SyncOperation" ADD CONSTRAINT "SyncOperation_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SyncConflict" ADD CONSTRAINT "SyncConflict_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportBatch" ADD CONSTRAINT "ImportBatch_shopId_fkey" FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE ON UPDATE CASCADE;
