import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import { pinoHttp } from "pino-http";
import { authenticate } from "./auth.js";
import { env } from "./config.js";
import { errorHandler, notFound } from "./http.js";
import { authRouter } from "./routes/auth.js";
import { resourcesRouter } from "./routes/resources.js";
import { syncRouter } from "./routes/sync.js";

export const app = express();
app.disable("x-powered-by");
app.use(pinoHttp());
app.use(helmet());
app.use(cors({ origin: env.WEB_ORIGIN, credentials: true }));
app.use(express.json({ limit: "2mb" }));
app.use(cookieParser());
app.use("/api/v1/auth", rateLimit({ windowMs: 60_000, limit: 20 }), authRouter);
app.get("/health", (_req, res) => res.json({ status: "ok" }));
app.use("/api/v1", authenticate, resourcesRouter);
app.use("/api/v1/sync", authenticate, syncRouter);
app.use(notFound);
app.use(errorHandler);
